openapi: 3.0.0
info:
  title: Admissions API Definition (OAS3)
  description: 'Declaring API services for the Admissions service.'
  contact:
    email: info@seemis.gov.scot
  version: '0.6.0'
servers:
  - url: https://9erbpduhe0.execute-api.eu-west-1.amazonaws.com/dev
    variables: {}
paths:
  "/admission/establishment/{establishmentId}/transfers/{transferId}":
    get:
      tags:
        - Establishment
      summary: "Returns the full details for the indicated transfer."
      description: "Returns the full details for the indicated transfer."
      operationId: getTransfer
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/student/{studentId}/status":
    get:
      tags:
        - Establishment
      summary: "Returns the enrolment status of the indicated student."
      description: "Returns the enrolment status of the indicated student at the provided establishment."
      operationId: getStudentStatus
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/studentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentStatus"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    put:
      tags:
        - Establishment
      summary: "Allows for the enrolment status of the indicated student to be updated."
      description: "Allows for the enrolment status of the indicated student to be updated."
      operationId: updateStudentStatus
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/studentIdParam"
      requestBody:
        description: "The selected admission status to update to."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentStatus"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/central/student/{studentId}/history":
    get:
      tags:
        - Central - Admission History
      summary: "Returns the full admission history for the indicated student."
      description: "Returns the full admission history for the indicated student."
      operationId: getAdmissionHistory
      parameters:
        - $ref: "#/components/parameters/studentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdmissionHistory"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/region/{regionId}/transfers/inbound":
    get:
      tags:
        - Region - Transfers
      summary: "Retrieves a list of inbound transfers within the region."
      description: "Retrieves a list of inbound transfers within the region."
      operationId: getInboundTransfersForRegion
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentTransfers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/region/{regionId}/transfers/outbound":
    get:
      tags:
        - Region - Transfers
      summary: "Retrieves a list of outbound transfers made within the region."
      description: "Retrieves a list of outbound transfers made within the region."
      operationId: getOutboundTransfersForRegion
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentTransfers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/region/{regionId}/transfers/rejected":
    get:
      tags:
        - Region - Rejected Transfers
      summary: "Retrieves a list of rejected transfers across the region."
      description: "Retrieves details on rejected student transfers from across the region."
      operationId: getRejectedTransfersForRegion
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentTransfers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/region/{regionId}/cme":
    get:
      tags:
        - Region - CME - Child Missing in Education
      summary: "Retrieves a list of students that have been marked as being subject to an ongoing CME investigation."
      description: "Retrieves a list of students that have been marked as being subject to an ongoing CME investigation."
      operationId: getCMEForRegion
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CMETableDetailsList"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    post:
      tags:
        - Region - CME - Child Missing in Education
      summary: "Indicates that a student has been marked as missing in education."
      description: "Indicates that a student has been marked as missing in education."
      operationId: assignCME
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
      requestBody:
        description: "Details of the missing in education flag to update."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CMEUpdate"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
  "/admission/region/{regionId}/cme/{studentId}":
    get:
      tags:
        - Region - CME - Child Missing in Education
      summary: "Retrieves the details of a student marked as being subject to an ongoing CME investigation."
      description: "Retrieves the details of a student marked as being subject to an ongoing CME investigation."
      operationId: getCMEForStudent
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
        - $ref: "#/components/parameters/studentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CMEDetails"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    put:
      tags:
        - Region - CME - Child Missing in Education
      summary: "Updates a CME flag for the student indicated by the transfer."
      description: "Updates a CME flag for the student indicated by the transfer"
      operationId: updateCME
      parameters:
        - $ref: "#/components/parameters/regionIdParam"
        - $ref: "#/components/parameters/studentIdParam"
      requestBody:
        description: "Details of the missing in education flag to update."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CMEUpdate"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound":
    get:
      tags:
        - Establishment - Transfers In
      summary: "Retrieves a list of inbound transfers for the establishment."
      description: "Retrieves details on inbound students from other establishments."
      operationId: getInboundTransfers
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentTransfers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/enrol/provisional":
    post:
      tags:
        - Establishment - Transfers In
      summary: "Provisionally enrols the indicated students into the establishment."
      description: "Transfers the indicated students into the establishment as a provisional enrolment."
      operationId: provisionalEnrolment
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Transfers to be accepted into the establishment."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AcceptedTransfers"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/enrol/full":
    post:
      tags:
        - Establishment - Transfers In
      summary: "Fully enrols the indicated students into the establishment."
      description: "Transfers the indicated students into the establishment as a full enrolment."
      operationId: fullEnrolment
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Transfers to be accepted into the establishment."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AcceptedTransfers"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admissions/establishment/{establishmentId}/transfers/inbound/enrol/exceptional":
    post:
      tags:
        - Establishment - Transfers In
      summary: "Creates a new student record where no previous record exists"
      description: "Creates a new student record intended to start at a chosen establishment where no previous record exists."
      operationId: newStudentRecord
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Details of the new student to be entered into the system."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transfer"
      responses:
        "201":
          description: "201 Created"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/update":
    post:
      tags:
        - Establishment - Transfers In
      summary: "Allows for details to be updated such as enrolment dates and student information."
      description: "Allows for details to be updated such as enrolment dates and student information."
      operationId: updateTransferInfo
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      requestBody:
        description: "Details of the transfer to be updated."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InboundTransferUpdates"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/reject":
    post:
      tags:
        - Establishment - Rejected Transfers
      summary: "Rejects the inbound transfers for the indicated student."
      description: "Rejects the inbound transfers for the indicated student."
      operationId: rejectTransfer
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Details of the transfers to reject."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RejectedTransfers"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/{transferId}/identification":
    post:
      tags:
        - Establishment - Transfers In
      summary: "Records which pieces of identification have been viewed by the establishment."
      description: "Records which pieces of identification have been viewed by the establishment."
      operationId: recordViewedIdentification
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      requestBody:
        description: "Which pieces of identification had been viewed."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ViewedIdentification"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/inbound/{transferId}/undo":
    put:
      tags:
        - Establishment - Transfers In
        - ⚠ Awaiting Clarification ⚠
      summary: "Reverses a full or provisional enrolment made in error."
      description: "Reverses a full or provisional enrolment made in error."
      operationId: undoEnrolment
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/workflow":
    get:
      tags:
        - Establishment - Transfers In - Workflow
        - ⚠ Awaiting Clarification ⚠
      summary: "Retrieves the sections to be completed post-enrolment."
      description: "Provides information on whether matriculation, year stage, individual options, and student groups are to be defined part of a student's enrolment."
      operationId: getWorkflow
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdmissionsWorkflow"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"


  "/admission/establishment/{establishmentId}/transfers/outbound":
    get:
      tags:
        - Establishment - Transfers Out
      summary: "Retrieves outbound transfers for the establishment."
      description: "Retrieves details on outbound students leaving the establishment."
      operationId: getOutboundTransfers
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentLeavers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    post:
      tags:
        - Establishment - Transfers Out
      summary: "Marks the indicated student as a leaver from the establishment."
      description: "Marks the indicated student as a leaver from the establishment."
      operationId: markLeaver
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Leaver object"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Leaver"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/outbound/update":
    post:
      tags:
        - Establishment - Transfers Out
      summary: "Allows for updating of leaver details including destination and reason for leaving."
      description: "Allows for updating of leaver details including destination and reason for leaving."
      operationId: updateLeaver
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Updated transfer"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaverDetails"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/outbound/cancel":
    post:
      tags:
        - Establishment - Transfers Out
      summary: "Cancels a leaver - removes the outgoing transfer for the student."
      description: "Cancels a leaver - removes the outgoing transfer for the student."
      operationId: cancelLeaver
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        description: "Cancelled leaver"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CancelLeaver"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/rejected":
    get:
      tags:
        - Establishment - Rejected Transfers
      summary: "Retrieves rejected transfers created by the establishment."
      description: "Retrieves details on transfers rejected by other establishments."
      operationId: getRejectedTransfers
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstablishmentLeavers"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
         
  "/admission/establishment/{establishmentId}/transfers/student/{studentId}/subsidiary":
    get:
      tags:
        - Establishment - Subsidiary Transfers
      summary: "Retrieves details on the student's main establishment and any other establishments being attended."
      description: "Retrieves details on the student's main establishment and any other establishments being attended."
      operationId: getSubsidiaryTransferInformation
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/studentIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentSubsidiaryTransferDetails"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"      

  "/admission/establishment/{establishmentId}/transfers/subsidiary":
    post:
      tags:
        - Establishment - Subsidiary Transfers
      summary: "Creates a subsidiary transfer to another establishment."
      description: "Creates a subsidiary transfer (copied record, 02 status) to another establishment."
      operationId: createSubsidiaryTransfer
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubsidiaryTransfer"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
          
  "/admission/establishment/{establishmentId}/transfers/subsidiary/{transferId}/update":
    put:
      tags:
        - Establishment - Subsidiary Transfers
      summary: "Updates the details of a subsidiary transfer in another establishment."
      description: "Updates the subsidiary transfer (copied record, 02 status) in another establishment. This will typically be used for updating the end date."
      operationId: updateSubsidiaryTransfer
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSubsidiaryTransfer"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

  "/admission/establishment/{establishmentId}/transfers/subsidiary/{transferId}/close":
    put:
      tags:
        - Establishment - Subsidiary Transfers
      summary: "Closes a subsidiary transfer in another establishment."
      description: "Closes the subsidiary transfer (copied record, 02 status) in another establishment. This operation is carried out by the student's main establishment, and not by the establishment holding the subsidiary record."
      operationId: closeSubsidiaryTransfer
      parameters:
        - $ref: "#/components/parameters/establishmentIdParam"
        - $ref: "#/components/parameters/transferIdParam"
      responses:
        "200":
          description: "200 Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"

components:
  schemas:
    AcceptedTransfer:
      title: Accepted Transfer
      description: A transfer being accepted into the establishment.
      allOf:
      - $ref: "#/components/schemas/TransferBasicDetails"
      - type: object
        properties:
          startDateInEstab:
            type: string

    AcceptedTransfers:
      title: Accepted Transfers
      description: List of transfers being accepted into the establishment.
      type: array
      items:
        $ref: "#/components/schemas/AcceptedTransfer"
  
    Address:
      title: Address
      required:
        - uprnRef
        - addressLine1
        - town
        - postcode
      type: object
      properties:
        addressid:
          type: string
        uprnRef:
          type: string
        houseflatno:
          type: string
          nullable: true
        addressLine1:
          type: string
        addressLine2:
          type: string
          nullable: true
        town:
          type: string
        postcode:
          type: string
        county:
          type: string
          nullable: true
        uuid:
          $ref: '#/components/schemas/UUID'
    
    AdmissionHistory:
      title: Admission History
      description: List of admission records associated with the student.
      type: object
      properties:
        history:
          type: array
          items:
            $ref: "#/components/schemas/AdmissionRecord"
    
    AdmissionRecord:
      title: Admission Record
      type: object
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        estabFrom:
          type: string
        estabTo:
          type: string
        reasonForLeaving:
          type: string
        status:
          $ref: "#/components/schemas/StudentStatus"
          
    AdmissionsWorkflow:
      title: Admissions Workflow
      description: Indicators for what sections will be made available to allow for additional information to be entered alongside enrolment.
      type: object
      
    Alert:
      title: Alert
      description: An alert regarding admissions data. Holds resource identifiers to allow possibility of drill-down.
      allOf:
        - $ref: "#/components/schemas/StudentBase"
        - type: object
          properties:
            knownAs:
              type: string
            surname:
              type: string
            stage:
              type: string
            fromEstab:
              type: string
            destEstab:
              type: string
            transferId:
              type: string
            when:
              type: string
              format: date
            alertType:
              $ref: "#/components/schemas/AlertType"

    AlertType:
      title: Alert Type
      description: Indicator of what type of alert has been received at the school.
      type: string
      enum:
        - INBOUND_TRANSFER
        - INBOUND_SUBSIDIARY_TRANSFER
        - LEAVER_DID_NOT_START
        - PROVISIONAL_ENROLMENT_DID_NOT_START
        - TRANSFER_REJECTED
          
    ApiDetails:
      title: API Response
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string

    CancelLeaver:
      title: Cancel Leaver
      description: Representation of an outgoing transfer from the establishment that is to be cancelled.
      allOf:
        - $ref: "#/components/schemas/StudentBase"
        - type: object
          properties:
            transferId:
              type: string
            studentId:
              type: string
            cancelReason:
              type: string

    CMEBasicDetails:
      title: Child Missing in Education - Basic Details
      description: Basic representation of a student who has been marked as missing in education.
      properties:
        student:
          $ref: "#/components/schemas/TransferBasicDetails"
        cmeDetails:
          $ref: "#/components/schemas/CMEInformation"

    CMETableDetails:
      title: Child Missing in Education - Table Details
      description: Basic representation of a student who has been marked as missing in education to be displayed in a table.
      properties:
        studentTransfer:
          $ref: "#/components/schemas/TransferBasicDetails"
        cmeDetails:
          $ref: "#/components/schemas/CMEInformation"

    CMETableDetailsList:
      title: Child Missing in Education - Table Details List
      description: List of objects representing the basic details of a student marked with the CME flag.
      properties:
        cmeList:
          type: array
          items:
            $ref: "#/components/schemas/CMETableDetails"

    CMEDetails:
      title: Child Missing in Education - Full Details
      description: Representation of a student who has been marked as missing in education.
      allOf:
      - $ref: "#/components/schemas/CMEBasicDetails"
      - type: object
        properties:
          leavingDate:
            type: string
            format: date
          rejectedByEstab:
            type: string
          rejectedReason:
            type: string
          rejectedDate:
            type: string
            format: date
          lac:
            type: boolean
          nonContact:
            type: boolean
          childProtection:
            type: boolean

    CMEInformation:
      title: Child Missing in Education - Information
      description: Object containing fields to update a Child Missing in Education investigation.
      properties:
        cmeOngoing:
          type: boolean
        cmeFrom:
          type: string
          format: date
        cmeResolved:
          type: string
          format: date
        cmeNotes:
          type: string
        estabFrom:
          type: string
        estabTo:
          type: string

    CMEUpdate:
      title: Child Missing in Education - Update
      properties:
        studentTransfer:
          $ref: "#/components/schemas/StudentTransfer"
        cmeDetails:
          $ref: "#/components/schemas/CMEInformation"

    Error:
      title: Error
      description: "An object detailing the generation of an error in the application"
      type: object
      properties:
        errorType:
          type: string
        errorCode:
          type: string
        requestId:
          type: string
        message:
          type: string
        detail:
          type: string
      required:
        - errorCode
        
    ErrorResponse:
      title: Error Response
      description: "A response object detailing the generation of one or many errors in the application"
      type: object
      properties:
        httpStatus:
          type: integer
          format: int32
        errorList:
          type: array
          items:
            $ref: "#/components/schemas/Error"
      required:
        - httpStatus

    EstablishmentLeavers:
      title: Establishment Leavers
      description: List of Leaver objects representing outbound transfers from the establishment.
      properties:
        outboundTransfers:
          type: array
          items:
            $ref: "#/components/schemas/TransferBasicDetails"
            
    EstablishmentTransfers:
      title: Establishment Transfers
      description: List of Transfer objects representing inbound transfers to the establishment.
      properties:
        inboundTransfers:
          type: array
          items:
            $ref: "#/components/schemas/TransferBasicDetails"

    IdentificationType:
      title: Identification Type
      type: string
      enum:
        - BIRTH_CERTIFICATE
        - PASSPORT
        - CITIZENSHIP
        - OTHER_PROOF_OF_ADDRESS

    InboundTransferUpdate:
      title: Transfer Update
      description: Updates to be made to an incoming transfer.
      type: object
      properties:
        transferId:
          type: string
        startDate:
          type: string
          format: date
          nullable: true
        stage:
          type: string
          nullable: true
        status:
          $ref: "#/components/schemas/StudentStatus"
          
    InboundTransferUpdates:
      title: Inbound Transfer Updates
      description: Collection of transfers to be updated.
      type: array
      items:
        $ref: "#/components/schemas/InboundTransferUpdate"

    Leaver:
      title: Leaver
      allOf:
      - $ref: "#/components/schemas/LeaverDetails"
      - type: object
        properties:
          studentId:
            type: string
            
    LeaverDetails:
      title: Leaver Details
      type: object
      properties:
        intendedLeaveDate:
          type: string
          format: date
        actualLeaveDate:
          type: string
          format: date
        intendedDestination:
          type: string
        reasonForLeaving:
          type: string
          nullable: true
        confidential:
          type: boolean
          nullable: true
        transferNotes:
          type: string
          nullable: true
        sixteenPlus:
          $ref: "#/components/schemas/SixteenPlus"

    RejectedTransfers:
      title: Rejected Transfers
      description: List of transfers from the establishment that have been rejected.
      type: array
      items:
        $ref: "#/components/schemas/RejectedTransfer"

    RejectedTransfer:
      title: Rejected Transfer
      description: A transfer from the establishment that has been rejected.
      allOf:
      - $ref: "#/components/schemas/TransferBasicDetails"
      - type: object
        properties:
          rejectReason:
            type: string
          rejectedWhen:
            type: string
            format: date

    SixteenPlus:
      title: Sixteen Plus
      description: Data to be provided when student is being transferred out from school when over minimum leaving age. Prelimiary 16+ data is supplied as part of the Student Records service.
      type: object
      properties:
        status:
          type: string
        startDate:
          type: string
          format: date
        trainingOrganisation:
          type: string
          nullable: true
        employer:
          type: string
          nullable: true
        jobTitle:
          type: string
          nullable: true
        usePreferredRoute:
          type: boolean
        conditional:
          type: boolean
          nullable: true
        academicDestination:
          type: string
          nullable: true
        
    StudentBase:
      title: Student Base
      type: object
      properties:
        studentId:
          $ref: "#/components/schemas/UUID"

    Person:
      title: Person
      required:
        - forename
        - surname
      type: object
      properties:
        uuid:
          type: string
        forename:
          type: string
        surname:
          type: string
        middleNames:
          type: string
        knownAsForename:
          type: string
        knownAsSurname:
          type: string
      example:
        $ref: '#/components/examples/PersonExample'

    StudentBasicDetails:
      title: Student Basic Details
      allOf:
      - $ref: "#/components/schemas/StudentBase"
      - type: object
        properties:
          dob:
            type: string
            format: date
          stage:
            type: string
            enum:
              - P1
              - P2
              - P3
              - P4
              - P5
              - P6
              - P7
              - S1
              - S2
              - S3
              - S4
              - S5
              - S6
              - S7
              - S8
              - S9
              - AD
              - SP
          sex:
            type: string
            enum:
              - Male
              - Female
          gender:
            type: string
            enum:
              - Male
              - Female
              - Unknown
              - Withheld
          person:
            $ref: '#/components/schemas/Person'
        example:
          $ref: '#/components/examples/StudentExample'
        
    StudentDetails:
      title: Student Details
      allOf:
      - $ref: "#/components/schemas/StudentBasicDetails"
      - type: object
        properties:
          middleNames:
            type: array
            items:
              type: string
          scn:
            type: string
          identificationType:
            type: array
            items:
              $ref: "#/components/schemas/IdentificationType"
          previousSurnames:
            type: array
            items:
              type: string

    StudentStatus:
      title: Student Admission Status
      type: object
      properties:
        status:
          type: string
        description:
          type: string

    StudentSubsidiaryTransferDetails:
      title: Student Subsidiary Transfer Details
      description: Identifiers of the student's main establishment and any other establishments attended via subsidiary transfers.
      type: object
      properties:
        mainEstablishment:
          type: string
        secondaryEstablishments:
          type: array
          items:
            type: string
      example:
        $ref: '#/components/examples/SubsidiaryDetailsExample'

    SubsidiaryTransfer:
      title: Subsidiary Transfer
      description: A transfer to another establishment to act as a secondary teaching environment.
      allOf:
      - $ref: "#/components/schemas/StudentBase"
      - type: object
        properties:
          destEstab:
            type: string
          startDate:
            type: string
            format: date
          endDate:
            type: string
            format: date         

    StudentTransfer:
      title: Student Transfer
      type: object
      properties:
        studentId:
          $ref: "#/components/schemas/UUID"
        transferId:
          type: string

    Transfer:
      title: Transfer
      allOf:
      - $ref: "#/components/schemas/TransferBasicDetails"
      - type: object
        properties:
          student:
            $ref: "#/components/schemas/StudentDetails"
          address:
            $ref: "#/components/schemas/Address"
          telephoneNumber:
            type: string
          transferEstab:
            type: string
          mainEstab:
            type: string
          secondaryEstab:
            type: string
          startDateInEstab:
            type: string
            format: date
          lookedAfterChildrenStatus:
            type: boolean
          nonDisclosureStatus:
            type: boolean
        example:
          $ref: '#/components/examples/TransferExample'

    TransferBasicDetails:
      title: Transfer Basic Details
      description: Basic identifier of transfer.
      allOf:
      - $ref: "#/components/schemas/StudentTransfer"
      - type: object
        properties:
          estabFrom:
            type: string
          estabTo:
            type: string
          expectedStartDate:
            type: string
            format: date
        example:
          $ref: '#/components/examples/TransferBasicExample'

    UpdateSubsidiaryTransfer:
      title: Updated Subsidiary Transfer
      description: An update to the subsidiary transfer in another establishment.
      allOf:
      - $ref: "#/components/schemas/SubsidiaryTransfer"
      - type: object
        properties:
          transferId:
            type: string
 
    UUID:
      title: UUID
      description: A system generated unique identifier for an Entity - all Entities are guaranteed to have a globally unique id
      type: string
      format: uuid
      example: "aac67fef-07df-47fc-b268-82e6834ff735"
      
    ViewedIdentification:
      title: Viewed Identification
      description: One or more pieces of identification required to register a student that have been viewed by the authority.
      type: array
      items:
        $ref: "#/components/schemas/IdentificationType"
        
  parameters:
    establishmentIdParam:
      name: establishmentId
      in: path
      description: "ID of establishment"
      required: true
      schema:
        type: string
    regionIdParam:
      name: regionId
      in: path
      description: "ID of region"
      required: true
      schema:
        type: string
    publicIdentifierIdParam:
      name: publicIdentifierId
      in: path
      description: "ID for public identifier record"
      required: true
      schema:
        type: string
    studentIdParam:
      name: studentId
      in: path
      description: "ID of student"
      required: true
      schema:
        type: string
    transferIdParam:
      name: transferId
      in: path
      description: "ID of transfer"
      required: true
      schema:
        type: string

  examples:
    PersonExample:
      value:
        uuid: 64ecf8ef-7584-4d21-9d7f-923e6087087c
        forename: Eilidh
        surname: McEwan
        middleNames: Harriet
        knownAsForename: Eilidh
        knownAsSurname: McEwan
    StudentExample:
      value:
        dob: '2007-03-01'
        stage: 'S2'
        sex: 'Female'
        gender: 'Female'
        person:
          $ref: '#/components/examples/PersonExample'

    AddressExample:
      value:
        addressid: '326682e7-87f6-4ac4-ad8e-8b8164c97696'
        uprnRef: '100546'
        addressLine1: 'Flat 3/2'
        addressLine2: '72 New Road'
        town: 'ExampleTown'
        postcode: 'ML3 0AA'
        county: 'ExampleCounty'
        uuid: 'b1e33a4b-38a2-4732-99e6-504a8c6d6273'

    SubsidiaryDetailsExample:
      value:
        mainEstablishment: '66232e40-62a0-4b00-92e6-c4bc9740de1a'
        otherEstablishments: ['66232e40-62a0-4b00-92e6-c4bc9740de1a', '66232e40-62a0-4b00-92e6-c4bc9740de1a']
          
    TransferExample:
      value:
        estabFrom: '66232e40-62a0-4b00-92e6-c4bc9740de1a'
        estabTo: '27951236-ac07-46f9-ab56-6f8d62e65f55'
        expectedStartDate: '2020-02-04'
        transferId: '768126e8-18aa-4669-90ea-bc59e531b261'
        student:
          $ref: '#/components/examples/StudentExample'
        address:
          $ref: '#/components/examples/AddressExample'
        telephoneNumber: '07442 111110'
        transferEstab: '66232e40-62a0-4b00-92e6-c4bc9740de1a'
        mainEstab: '27951236-ac07-46f9-ab56-6f8d62e65f55'
        startDateInEstab: '2020-02-04'
        lookedAfterChildrenStatus: 'false'
        nonDisclosureStatus: 'false'
      
    TransferBasicExample:
      value:
        estabFrom: '66232e40-62a0-4b00-92e6-c4bc9740de1a'
        estabTo: '66232e40-62a0-4b00-92e6-c4bc9740de1a'
        expectedStartDate: '2020-02-04'
        transferId: '768126e8-18aa-4669-90ea-bc59e531b261'
        studentId: 'b1e33a4b-38a2-4732-99e6-504a8c6d6273'

  responses:
    SuccessCreatedResponse:
      description: "201 Success - Created"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        content:
            schema:
              $ref: "#/components/schemas/ApiDetails"
    SuccessNoContentResponse:
      description: "204 Success - No Content"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
    BadRequestResponse:
      description: "400 Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    UnauthorizedResponse:
      description: "401 Unauthorized"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ForbiddenResponse:
      description: "403 Forbidden"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFoundResponse:
      description: "404 Not Found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

tags:
  - name: Establishment
    description: Admissions services specific to an establishment.
  - name: Establishment - Transfers In
    description: Admissions services regarding transfers into an establishment.
  - name: Establishment - Transfers In - Workflow
    description: Admissions services regarding workflow retrieval.
  - name: Establishment - Transfers Out
    description: Admissions services regarding transfers out from an establishment.
  - name: Establishment - Subsidiary Transfers
    description: Admissions services regarding subsidiary transfers to a second establishment.
  - name: Establishment - Rejected Transfers
    description: Admissions services regarding rejecting transfers and viewing rejected transfers on an establishment level.
  - name: Region - CME - Child Missing in Education
    description: Admissions services regarding the 'Child Missing in Education' indicator.
  - name: Region - Transfers
    description: Admissions services regarding viewing inbound and outbound transfers made within the indicated region.
  - name: Region - Rejected Transfers
    description: Admissions services regarding viewing rejected transfers on a regional level.
  - name: Central - Admission History
    description: Admissions services regarding retrieval of a student's admission history.
  - name: ⚠ Awaiting Clarification ⚠
    description: Endpoints that need further clarification or are candidates for removal.
externalDocs:
  description: Link to addition info, e.g. wiki or serverless portal
  url: http://swagger.io
